name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.x
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 15.11.x

      - name: Building static assets
        run: (cd client && yarn install --immutable && yarn build)

      - name: Build
        run: |
          go generate ./...
          go build -v .

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0
          ./bin/golangci-lint run -D errcheck

      - name: Test
        run: go test -race -coverprofile=./c.out -covermode=atomic -v ./...

      - name: Report code coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=./c.out -service=github
