
def mainMenu():
    print("+--------------------------------------------------------------+")
    print("Choose an option:" + '\n')
    print("--shell  Get a shell")
    print("--ginfo  Get target info")
    print("--shutdown  Shutdown target")
    print("--close  Close connection")
    print("--screenshot  Take a screenshot")
    print("--upload  Upload a file to the victim's machine")
    print("--download  Download victim's files")
    print("--run  Run python scrypt on the victim's machine")
    print("--kill  Kill processes")
    print("--msg  Open message box")
    print("--lock  Lock PC")
    print("--stop  Stop key logger")
    print("--ccb  Get clipboard content")
    print("--getlogs  Get key logger logs" + '\n')
    print("Exit")
    print("__________________________-------------------------------------------")
